wallpaper {
    monitor = eDP-1
    path = /home/tuna/.config/hypr/wallpapers/wallpaper-arch-ascii.png
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = /home/tuna/.config/hypr/wallpapers/wallpaper-arch-ascii.png
    fit_mode = cover
}
splash = false
